### ISSUE TITLE
Doesnt Comply with PGPOnline.org 

### ISSUE THREAD

**Issue by bkumar18** [MrLeebo/PgpEncryptor#1]
Hi,

I have a requirement where I take a simple text file, use the PGPEncryptor library to encrypt the file using the public key and our vendor/ client would use the PGPonline.org tool to decrypt using the private key.

Unfortunately while I decypt the encrypted file that was done via the PGPEncryptor library I get the following error:

Message failed to verify!
Error: no header found

(Unfortunately I cannot pass the text file or the Pvt key for testing).. 

Appreciate any help in this regards.

Thanks
Kumar

**Comment by MrLeebo** [comment]
Kumar,

If you feel like something is missing in this library, feel free to open a pull request, as I won't be making any changes. I don't know what PGPonline.org is, and there doesn't appear to be a site with that domain name. There's a pretty good chance that your requirement wasn't referring to this package, probably some other PGP library instead. This package was really just an excuse for me to familiarize myself with Nuget package manager. However, I am not currently doing development in C#. If you think the code is still useful for you, feel free to copy the [source code](https://github.com/MrLeebo/PgpEncryptor/blob/master/PgpEncryptor/Encryptor.cs) and modify it for your requirements.
